---
version: 1.5.1
slug: unbound
name: unbound
description: A simple DNS server
url: https://github.com/home-assistant/addons/tree/master/unbound
advanced: true
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
init: false
ports:
  5335/tcp: 5335
  5335/udp: 5335
startup: system