#!/usr/bin/with-contenv bash
set -euo pipefail

exec chromium \
  --headless \
  --no-sandbox \
  --disable-gpu \
  --disable-dev-shm-usage \
  --remote-debugging-address=127.0.0.1 \
  --remote-debugging-port=9222 \
  --hide-scrollbars
