#!/usr/bin/with-contenv bash
set -euo pipefail

source /usr/local/bin/load-env.sh

mkdir -p \
  /data/cache \
  /data/postgres \
  /var/run/postgresql \
  /var/run/redis \
  "${IMMICH_MEDIA_LOCATION}"
