---
version: 2.10.0-r3
hassio_api: true
slug: caddy_proxy
name: Caddy Home Assistant SSL proxy
description: A reverse proxy using Caddy
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
map:
  - ssl
  - share
init: false
ports:
  443/tcp: 443
options:
  domain: null
  certfile: public.crt
  keyfile: private.key
  trusted_proxies: null
schema:
  domain: str
  certfile: str
  keyfile: str
  trusted_proxies: str
